# Generated by Django 3.1 on 2021-03-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='tracking_id',
            field=models.PositiveIntegerField(default='4kE96GV', editable=False),
        ),
    ]
