# Generated by Django 3.1 on 2021-03-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210331_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='tracking_id',
            field=models.CharField(default='BDuL6WN', editable=False, max_length=8),
        ),
    ]
